// Generated by CoffeeScript 1.10.0
(function () {
	var vscode = require('vscode');
	var ShareDB = require('sharedb/lib/client');
	var VSCodeShare, shareVSCodeEditor;

	shareVSCodeEditor = require('./vscode_attacher');

	VSCodeShare = (function () {
		function VSCodeShare(ws) {
			this.ws = ws;
			this.packageVersion = require('../package.json').version;
			this.sharedb = new ShareDB.Connection(this.ws);
		}

		VSCodeShare.prototype.start = function (sessionId) {
			this.ws.send(JSON.stringify({
				a: 'meta',
				type: 'init',
				sessionId: sessionId,
				vscodeVersion: vscode.version,
				motepairVersion: this.packageVersion
			}));
			return vscode.window.onDidChangeActiveTextEditor((function (_this) {
				return function (TextEditor) {
					var doc, relativePath;
					relativePath = vscode.workspace.asRelativePath(TextEditor.document.uri);
					doc = _this.sharedb.get('editors', sessionId + ":" + relativePath);
					return _this.setupDoc(doc, TextEditor);
				};
			})(this));
		};

		VSCodeShare.prototype.setupDoc = function (doc, TextEditor) {
			doc.subscribe();
			return doc.on('load', function () {
				var ctx;
				if (!doc.type) {
					var allTextRange = new vscode.Range(new vscode.Position(0, 0), TextEditor.document.lineAt(TextEditor.document.lineCount - 1).range.end);
    				var editorText = TextEditor.document.getText(allTextRange);
					doc.create(editorText, 'text');
				}
				if (doc.type && doc.type.name === 'text') {
					return shareVSCodeEditor(TextEditor, doc);
				}
			});
		};

		return VSCodeShare;

	})();

	module.exports = VSCodeShare;

}).call(this);
